# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72075b77dfbf8f44a07148d00c20166e776430e1a4ac512c884258e400dd3fd263f017b1bd0b0d82f0b74342ed54c925a762b3ab936b71241723606d3cdfaefd

test:
  secret_key_base: c53987f9e711897a472dc01a6a5ea5a3364c41063c564ed54ccac28c035a21ee76bd8a0567e5f95568f9c7fcccb62b4ac312d45ca8ede495ab7fb5ecfab99824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
